### ISSUE TITLE
dlopen() fails on Linux system

### ISSUE THREAD

**Issue by srherbener** [JCSDA/pyodc#5]
Unfortunately, I think we do need to add the |.so| suffix on linux/GNU
systems as dlopen in glibc is not smart enough to check for it
automatically. Here is an example from my home machine running
Python-3.7. I have |libodccore.so| installed to |/usr/lib64|. If I ask
to find |libodccore| it fails, but |libodccore.so| works.

Two possible fixes:
1.

|try: self.__lib = ffi.dlopen('libodccore') except OSError: self.__lib =
ffi.dlopen('libodccore.so')|

 2.

|lib_search_name="libodccore" if sys.platform.startswith('linux'):
lib_search_name+=".so" self.__lib = ffi.dlopen(lib_search_name)|

Here's what I'm seeing in python:

```
Python 3.7.7 (default, Apr 23 2020, 02:33:35) Type 'copyright',
'credits' or 'license' for more information IPython 7.5.0 -- An enhanced
Interactive Python. Type '?' for help. In [1]: import cffi In [2]:
ffi=cffi.FFI() In [3]: ffi.dlopen('libodccore')
---------------------------------------------------------------------------
OSError Traceback (most recent call last) <ipython-input-3-8b8d1795257b>
in <module> ----> 1 ffi.dlopen('libodccore')
/usr/lib/python3.7/site-packages/cffi/api.py in dlopen(self, name,
flags) 148 "or an already-opened 'void *' handle") 149 with self._lock:
--> 150 lib, function_cache = _make_ffi_library(self, name, flags) 151
self._function_caches.append(function_cache) 152
self._libraries.append(lib) /usr/lib/python3.7/site-packages/cffi/api.py
in _make_ffi_library(ffi, libname, flags) 830 def _make_ffi_library(ffi,
libname, flags): 831 backend = ffi._backend --> 832 backendlib =
_load_backend_lib(backend, libname, flags) 833 # 834 def
accessor_function(name): /usr/lib/python3.7/site-packages/cffi/api.py in
_load_backend_lib(backend, name, flags) 825 if first_error is not None:
826 msg = "%s. Additionally, %s" % (first_error, msg) --> 827 raise
OSError(msg) 828 return backend.load_library(path, flags) 829 OSError:
ctypes.util.find_library() did not manage to locate a library called
'libodccore' In [4]: ffi.dlopen('libodccore.so') Out[4]:
<cffi.api._make_ffi_library.<locals>.FFILibrary at 0x7f25858d6550> 
```

**Comment by srherbener** [comment]
@markjolah, I've updated the codc.py code to use "libodccore.so" for linux systems and "libodccore" for other systems in the dlopen() call.

This works on my Mac and on Ubuntu (in Singularity).

I moved the 1.0.1.jcsda2 tag to the commit with this fix.

**Comment by markjolah** [comment]
Work for me now.  Thanks @srherbener !
